### PR TITLE
Allow GENSRC_VARHANDLES in OpenJ9

### PR DESCRIPTION
**Pull request by babsingh**
`GENSRC_VARHANDLES` converts **X-VarHandle\*.template** files into Java files.

**X-VarHandle\*.template** files are located in the `java.lang.invoke` package
directory.

The generated Java files are needed for **JEP-370, Foreign Memory Access API**.

**JEP-370:** https://openjdk.java.net/jeps/370.

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>

### CODE REVIEW

**Comment by DanHeidinga** [comment]
Jenkins test sanity zlinux jdk14

**Comment by DanHeidinga** [comment]
@babsingh Can this file be removed?  It'll only contain copyright after this change. 

The caller is https://github.com/ibmruntimes/openj9-openjdk-jdk14/blob/2a23b447fca04a8bf7e39baedab2558658eb1640/make/gensrc/GensrcVarHandles.gmk#L282
which we'd have to confirm can handle a non-existant file

**Comment by babsingh** [comment]
@DanHeidinga Yes, removing `GensrcVarHandles-post.gmk` works. I have removed `GensrcVarHandles-post.gmk`. For the Jenkins sanity builds, we will need `depends eclipse/openj9#8330`.

**Comment by DanHeidinga** [comment]
Jenkins test sanity zlinux jdk14 depends eclipse/openj9#8330

**Comment by pshipton** [comment]
Jenkins test sanity zlinux jdk14 depends eclipse/openj9#8330

**Comment by babsingh** [comment]
@pshipton @DanHeidinga I will have to redo these changes since https://github.com/ibmruntimes/openj9-openjdk-jdk14/pull/12 relocates `GensrcVarHandles-post.gmk` from `closed/make/gensrc/GensrcVarHandles-post.gmk` to `...d/custom/gensrc/GensrcVarHandles-post.gmk`.

**Comment by pshipton** [comment]
Right. I stopped the build.

**Comment by babsingh** [comment]
@pshipton pull request updated. can you please restart the jenkins job? also, can you start an identical jenkins job in https://github.com/eclipse/openj9/pull/8330: `Jenkins test sanity zlinux jdk14 depends ibmruntimes/openj9-openjdk-jdk14#6`?

**Comment by pshipton** [comment]
Jenkins test sanity zlinux jdk14 depends eclipse/openj9#8330

**Review by DanHeidinga — APPROVED** [review]
lgtm

**Pull request merged**
