### PR TITLE
Add debug-image target

### PR DESCRIPTION
**Pull request by keithc-ca**
* copy debuginfo files for openj9 shared libraries
* collect files (*.debuginfo, *.pdb, etc.) into images/debug-image

### CODE REVIEW

**Comment by keithc-ca** [comment]
Jenkins test sanity aix,osx,zlinux,win jdk14

**Comment by keithc-ca** [comment]
Jenkins test sanity aix jdk14

**Comment by keithc-ca** [comment]
AIX testing appears to have completed successfully:
```
11:44:49  TOTAL: 289   EXECUTED: 171   PASSED: 171   FAILED: 0   DISABLED: 4   SKIPPED: 114
11:44:49  ALL TESTS PASSED
```
but it's been more than an hour since it began sharing the results:
```
11:45:06  TAP Reports Processing: START
11:45:06  Looking for TAP results report in workspace using pattern: **/*.tap
11:45:14  Saving reports...
11:45:14  Processing '/var/jenkins_home/jobs/Test_openjdk14_j9_sanity.functional_ppc64_aix_Personal/builds/4/tap-master-files/openjdk-tests/TKG/test_output_15828141992890/TestTargetResult.tap'
11:45:14  Parsing TAP test result [/var/jenkins_home/jobs/Test_openjdk14_j9_sanity.functional_ppc64_aix_Personal/builds/4/tap-master-files/openjdk-tests/TKG/test_output_15828141992890/TestTargetResult.tap].
11:45:14  TAP Reports Processing: FINISH
[Pipeline] junit
11:45:14  Recording test results
```

https://ci.eclipse.org/openj9/job/Test_openjdk14_j9_sanity.functional_ppc64_aix_Personal/4

**Comment by AdamBrousseau** [comment]
Looks like the machine disconnected. There is another test running (`#4`) from this pr.

**Comment by keithc-ca** [comment]
I was referring to job number 4 which still appears stuck.

**Comment by AdamBrousseau** [comment]
Apologies, not sure why 4 is hung. TAP file is 21k so I don't think it should be taking that long to process. No extra java processes lying around.

**Comment by keithc-ca** [comment]
Marking as 'WIP' until I correct the paths for `.dSYM` folders on OSX.

**Comment by keithc-ca** [comment]
The proper paths are now computed for all platforms.

**Comment by pshipton** [comment]
Jenkins test sanity aix,osx,plinux,win jdk14

**Review by pshipton — APPROVED** [review]

**Pull request merged**
